# Generated by Django 4.2.4 on 2023-08-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='time_created',
        ),
    ]
