# Generated by Django 4.2.4 on 2023-08-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_created_task_time_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='time_created',
            new_name='time_edited',
        ),
        migrations.AddField(
            model_name='task',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
